exercitos = {
    'Brasil': 0,
    'Argentina': 0,
    'Colombia': 0,
    'Peru': 0,
    'Mexico' : 0,
    'California' : 0,
    'NovaIorque' : 0,
    'Labrador' : 0,
    'Ottawa' : 0,
    'Vancouver' : 0,
    'Mackenzie' : 0,
    'Alasca' : 0,
    'Groelandia' : 0,
    'Islandia' : 0,
    'Inglaterra' : 0,
    'Suecia' : 0,
    'Alemanha' : 0,
    'Espanha' : 0,
    'Polonia' : 0,
    'Moscou' : 0,
    'Argelia' : 0,
    'Egito' : 0,
    'Congo' : 0,
    'Sudao' : 0,
    'Madagascar' : 0,
    'AfricadoSul' : 0,
    'OrienteMedio' : 0,
    'Aral' : 0,
    'Omsk' : 0,
    'Dudinka' : 0,
    'Siberia' : 0,
    'Tchita' : 0,
    'Mongolia' : 0,
    'Vladivostok' : 0,
    'China' : 0,
    'India' : 0,
    'Japao' : 0,
    'Vietna' : 0,
    'Borneu' : 0,
    'Sumatra' : 0,
    'NovaGuine' : 0,
    'Australia' : 0
    }