fronteiras = {
    'Brasil': ["Argentina","Colombia","Peru","Argelia"],
    'Argentina': ["Brasil","Peru"],
    'Colombia': ["Brasil","Peru","Mexico"],
    'Peru': ["Brasil","Argentina","Colombia"],
    'Mexico' : ["Colombia","California","NovaIorque"],
    'California' : ["Mexico","NovaIorque","Vancouver","Ottawa"],
    'NovaIorque' : ["Mexico","California","Vancouver","Ottawa","Labrador"],
    'Labrador' : ["NovaIorque","Ottawa","Groelandia"],
    'Ottawa' : ["California","NovaIorque","Vancouver","Labrador","Alasca","Mackenzie","Groelandia"],
    'Vancouver' : ["California","NovaIorque","Ottawa","Alasca","Mackenzie"],
    'Mackenzie' : ["Alasca","Vancouver","Ottawa","Groelandia"],
    'Alasca' : ["Vancouver","Ottawa","Mackenzie","Vladivostok"],
    'Groelandia' : ["Mackenzie","Ottawa","Labrador","Islandia"],
    'Islandia' : ["Groelandia","Suecia","Inglaterra"],
    'Inglaterra' : ["Islandia","Suecia","Alemanha","Espanha"],
    'Suecia' : ["Islandia","Inglaterra","Polonia","Moscou"],
    'Alemanha' : ["Inglaterra","Espanha","Polonia"],
    'Espanha' : ["Inglaterra","Alemanha","Polonia","Argelia","Egito"],
    'Polonia' : ["Suecia","Alemanha","Espanha","Moscou","Egito"],
    'Moscou' : ["Suecia","Polonia","Omsk","Aral","OrienteMedio"],
    'Argelia' : ["Brasil","Egito","Sudao","Congo","Espanha"],
    'Egito' : ["Argelia","Sudao","OrienteMedio","Espanha","Polonia"],
    'Congo' : ["Argelia","Sudao","AfricadoSul"],
    'Sudao' : ["Argelia","Egito","Congo","Madagascar"],
    'Madagascar' : ["Sudao","AfricadoSul"],
    'AfricadoSul' : ["Congo","Madagascar"],
    'OrienteMedio' : ["Egito","India","Aral","Moscou"],
    'Aral' : ["OrienteMedio","India","Mongolia","Dudinka","Omsk","Moscou"],
    'Omsk' : ["Moscou","Siberia","Dudinka","Mongolia","Aral"],
    'Dudinka' : ["Omsk","Aral","Mongolia","China","Tchita","Siberia"],
    'Siberia' : ["Omsk","Dudinka","Tchita","Vladivostok"],
    'Tchita' : ["Siberia","Dudinka","Mongolia","China","Vladivostok"],
    'Mongolia' : ["Omsk","Aral","India","China","Tchita","Dudinka"],
    'Vladivostok' : ["Siberia","Tchita","China","Japao","Alasca"],
    'China' : ["Dudinka","Mongolia","India","Vietna","Japao","Vladivostok","Tchita"],
    'India' : ["Aral","OrienteMedio","Mongolia","China","Vietna"],
    'Japao' : ["Vladivostok","China"],
    'Vietna' : ["India","China","Borneu","Sumatra"],
    'Borneu' : ["Vietna","Australia","NovaGuine","Sumatra"],
    'Sumatra' : ["Vietna","Borneu","Australia"],
    'NovaGuine' : ["Borneu","Australia"],
    'Australia' : ["Borneu","Sumatra","NovaGuine"]
    }